### PR TITLE
Document Module#br command and add Module#break to index.d.ts

### PR DESCRIPTION
**Pull request by drew-y**
Hey! I noticed that **Module#break** wasn't in the index.d.ts file. So I went ahead and corrected index.d.ts. I also updated the README to document the **Module#br** alias.

One question though, should Module#break be included at all? I'm new to WASM, so I assumed it would behave like a normal break, which turned out not to be the case. Isn't `br` more accurate? Since its not really `break`ing (depending on the block it points to anyway). 

If so, I'd be happy to update the pull request to reflect that.

### CODE REVIEW

**Comment by dcodeIO** [comment]
> Isn't br more accurate?

Yes, `break` is a deprecated alias of `br`. The default nowadays is to use the variant reflecting WebAssembly text format, and the old aliases are likely to become removed at some point. Hence the `.d.ts` doesn't list them.

**Comment by drew-y** [comment]
Ahhh. That makes sense. Would you like me to update the README, or leave it as is and close the pull request?

**Comment by dcodeIO** [comment]
Sure, updating the README would be great. Did you spot any other mentions of deprecated aliases, or is `br` the only one?

**Comment by drew-y** [comment]
‘br’ is the only one so far. But I’ll spend some time looking for others, before I push the next update. 

The binaryen repo also only documents break in their wiki.

**Comment by drew-y** [comment]
I went through and this is the only deprecated alias I could find. 

I did notice there are lots of references to `BreakID` and `BreakInfo` in the README and index.d.ts. Those should probably be updated to `Br`, but [binaryen.js-post.js](https://github.com/WebAssembly/binaryen/blob/master/src/js/binaryen.js-post.js) still references them. So I'll submit a pull request there before updating.

**Comment by dcodeIO** [comment]
> I did notice there are lots of references to BreakID and BreakInfo in the README

Binaryen's internal C++ classes don't always map exactly to Wasm instructions. Take `Binary` for example that covers all kinds of binary expressions, and has a `BinaryId` and a `BinaryInfo`. Similarly, the class backing `br`s is `Break`. As such that's not necessarily connected to the more convenient instruction creation naming in JS.

**Comment by drew-y** [comment]
That's really good to know. Thanks! This pull request is ready to merge in that case. 

Sorry about the large discussion for such a small pr 😅.

**Comment by dcodeIO** [comment]
Thanks! :)

**Pull request merged**
