### PR TITLE
Add patched CMakeList which enables sign-ext & bulk-memory

### PR DESCRIPTION
**Pull request by MaxGraey**
Bulk memories was shipped in Chrome 75 (v8 7.5) and in Node.js 15.8.0. But our minimal requirements node.js 16.0.0

### CODE REVIEW

**Comment by dcodeIO** [comment]
Would it perhaps be preferable to enable these new features in Binaryen itself? Or even Emscripten by default?

**Comment by MaxGraey** [comment]
> Would it perhaps be preferable to enable these new features in Binaryen itself? Or even Emscripten by default?

I suggested this, but the point is that binaryen is originally designed for the lowest possible browser / node.js requirements. As you remember, migration from ES5 to ES6 for bindings was just recently

**Comment by dcodeIO** [comment]
Hmm, seems suboptimal, though, since the buildbot is what the upstream repository links to for JS builds, so if we enable it here we'd kinda overrule their intention. To me, it seems reasonable to enable features that are available in the major browsers *and* Node.js in the upstream repository so we stay in sync. Perhaps these requirements could be the convention for enabling features? @kripken wdyt?

**Comment by kripken** [comment]
I would be ok with this in Binaryen itself. That seems safer than to do something different here.

Emscripten testing should not be a problem (it doesn't run binaryen.js - only native builds). Binaryen testing might need a newer node, but that's all.

PR with that + documenting the requirements sgtm.

**Pull request closed without merging**
