### PR TITLE
Update APIs after instruction renaming

### PR DESCRIPTION
**Pull request by aheejin**
Companion with WebAssembly/binaryen#2128.

### CODE REVIEW

**Comment by aheejin** [comment]
Ping :) Can we merge this?

**Comment by dcodeIO** [comment]
Ah, of course, thank you! :)

**Comment by aheejin** [comment]
Thanks! To make it shown in README.md, do I need to run something manually?

**Comment by dcodeIO** [comment]
Yeah there is `npm run readme`. I'm currently updating the TypeScript definitions anyway, can run this later :)

**Pull request merged**
